# Generated by Django 2.2.7 on 2019-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20191120_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(default='hello'),
        ),
    ]
