# Generated by Django 2.2.7 on 2019-11-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
