# Generated by Django 2.2.7 on 2019-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20191123_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='create_user',
            new_name='create_worker',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='edit_user',
            new_name='edit_worker',
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_access',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
