# Generated by Django 2.2.7 on 2019-11-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20191125_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='enable_sale',
            field=models.BooleanField(default=True),
        ),
    ]
