# Generated by Django 2.2.7 on 2019-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_worker_enable_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date_log',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='enable_sale',
            field=models.BooleanField(),
        ),
    ]
