# Generated by Django 2.2.7 on 2019-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20191127_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AddField(
            model_name='sale',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='worker_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='edit_time',
            field=models.DateTimeField(),
        ),
    ]
