# Generated by Django 2.2.7 on 2019-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20191129_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='parent_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
