# Generated by Django 2.2.7 on 2019-11-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_sale_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='parent_id',
            new_name='creater_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='create_worker',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='edit_worker',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='editer_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='create_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='edit_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
