# Generated by Django 2.2.7 on 2019-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20191130_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='edit_user',
        ),
        migrations.AddField(
            model_name='stock',
            name='creater_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='editer_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='create_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='edit_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
