# Generated by Django 2.2.7 on 2019-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20191203_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
