# Generated by Django 2.2.7 on 2019-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
