# Generated by Django 2.2.7 on 2019-12-04 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_sale_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('type', models.SlugField(choices=[('income', 'income'), ('expense', 'expense')])),
                ('volume', models.PositiveIntegerField()),
                ('creater_id', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField()),
                ('editer_id', models.PositiveIntegerField()),
                ('edit_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
